export const singleProductImagesData = [
  {
    title: "Metal",
    image1: "",
    image2: "",
    image3: "",
    image4: "",
    content1: "",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
  },
  {
    title: "Consumer Goods",
    image1: "",
    image2: "",
    image3: "",
    image4: "",
    content1: "",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
  },
  {
    title: "Agricultural Goods",
    image1: "",
    image2: "",
    image3: "",
    image4: "",
    content1: "",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
  },
  {
    title: "Paper",
    image1: "",
    image2: "",
    image3: "",
    image4: "",
    content1: "",
    content2: "",
    content3: "",
    content4: "",
    content5: "",
  },
];
